[project]
name = "EdgeOneDynamicOrigin"
version = "0.1.0"
description = "EdgeOneDynamicOrigin"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "PyYAML",
    "streamlit"
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
